# Generated by Django 5.1.2 on 2024-10-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_board_description_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='commit_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
